tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: atixd.me
    service: http://portfolio:3000
  - hostname: www.atixd.me
    service: http://portfolio:3000
  - service: http_status:404
